""for ueda
set encoding=utf-8
set fileencodings=iso-2022-jp,iso-2022-jp-2,utf-8,euc-jp,sjis



set ts=4 
set scrolloff=0 
set sidescrolloff=0 
set sidescroll=0 
set nocursorline 
set cmdheight=1 
set nowrap 
set virtualedit+=block 
set autoread 
set tw=0 
set expandtab 
set ignorecase 
set smartcase 
set nu 
set noautoindent 
"set smartindent 
set nocompatible 
set whichwrap=b,s,h,l,<,>,[,] 
set backspace=indent,eol,start 
nmap ff :ls<CR>:b
nmap <C-l> :bn<CR>
nmap <C-h> :bp<CR>
nmap <C-p> :bd<CR>:vs<CR>:set fdc=1<CR>
map <C-j> <C-E><C-E>
map <C-k> <C-Y><C-Y>
nmap / /\v
vnoremap <silent> <C-p> "0p
let @m=':set virtualedit=block0'
let @h=':set virtualedit=all78zl'
ret @p='viwn'
nnoremap <space> i<space><esc>
"highlight Statement term=bold ctermbg=7 ctermfg=0
set fdc=1
nnoremap <C-W><C-F> <C-W><C-F><C-W><S-L>

set tags=.tags,tags
nnoremap <C-]> g<C-]>

set nobackup
set noundofile


" Save fold settings.
autocmd BufWritePost * if expand('%') != '' && &buftype !~ 'nofile' | mkview | endif
autocmd BufRead * if expand('%') != '' && &buftype !~ 'nofile' | silent loadview | endif
" Don't save options.
set viewoptions-=options

